# Generated by Django 4.0.4 on 2022-04-23 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_item_stored_box_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='items',
        ),
    ]
