# Generated by Django 4.0.4 on 2022-04-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_box_items'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.box'),
        ),
    ]
