# Generated by Django 4.0.4 on 2022-04-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_item_managers_item_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='items',
            new_name='boxed',
        ),
    ]
